# Optimized Dockerfile to install samtools from source
# 190MB image using optimized approach 

# use latest Ubuntu base image
FROM ubuntu:latest AS builder

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libbz2-dev \
    liblzma-dev \
    libncurses5-dev \
    wget \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# download samtools
ADD https://github.com/samtools/samtools/releases/download/1.23/samtools-1.23.tar.bz2 /samtools-1.23.tar.bz2

# install samtools
RUN tar -oxjf samtools-1.23.tar.bz2 && \
    cd samtools-1.23 && \
    ./configure --prefix=/temp/samtools && \
    make && \
    make install

# view dependencies
# RUN ldd /temp/samtools/bin/samtools

# create minimal image. (Alpine uses musl which is not compatible with glibc binaries)
FROM debian:stable-slim

# install libncurses dependency
# clean up apt-cache to reduce image size
RUN apt update && apt install -y --no-install-recommends \
    libncursesw6 \
    && rm -rf /var/lib/apt/lists/*

# copy from builder install location
COPY --from=builder /temp/samtools /usr/share/samtools

# create symlink so samtools is in PATH
# RUN ln -s /usr/share/samtools/bin/samtools /usr/bin/samtools
ENV PATH="/usr/share/samtools/bin:${PATH}"

RUN which samtools
RUN samtools --version
# verify installation
# CMD ["samtools", "--version"]